// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfferService.Infrastructure.Data;

#nullable disable

namespace OfferService.Infrastructure.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20260102142637_AddMissingColumnsForced")]
    partial class AddMissingColumnsForced
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.Property<long>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OfferId"));

                    b.Property<string>("AirbagsDeployed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AllTiresInflated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyPanelsIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("BuyerZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DrivetrainCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineTransmissionCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FloodFireDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InteriorIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMileageUnverifiable")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyOrFobAvailable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("MirrorsLightsGlassIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NoSQLIndexId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipTitleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerNetworkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("offered");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleBodyStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleBodyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleCabType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VehicleDoorCount")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleFuelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleTrim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleUsage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("WheelsRemoved")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WheelsRemovedDriverFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedDriverRear")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerRear")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkingBatteryInstalled")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OfferId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SellerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 35, 771, DateTimeKind.Utc).AddTicks(5210),
                            Email = "john.doe@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 35, 771, DateTimeKind.Utc).AddTicks(5217),
                            Name = "John Doe",
                            PasswordHash = "$2a$11$7faO2XQwCbC74b/E7wr4YetSbTbDTMMbAlZYQe..ZzdRMA0O4isj2"
                        },
                        new
                        {
                            SellerId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 35, 911, DateTimeKind.Utc).AddTicks(1522),
                            Email = "jane.smith@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 35, 911, DateTimeKind.Utc).AddTicks(1529),
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$lSa0MCVPAclsTU2rwvy3n.n4MV.nAVTyJ4qGdGPD0e/2vUFRfagby"
                        },
                        new
                        {
                            SellerId = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 65, DateTimeKind.Utc).AddTicks(5626),
                            Email = "bob.johnson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 65, DateTimeKind.Utc).AddTicks(5631),
                            Name = "Bob Johnson",
                            PasswordHash = "$2a$11$nqM6msPzje7ys234vJLWK.5GNh.JMj7GQrBn.we.ZpEfnhoin.kcC"
                        },
                        new
                        {
                            SellerId = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 237, DateTimeKind.Utc).AddTicks(6581),
                            Email = "alice.williams@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 237, DateTimeKind.Utc).AddTicks(6589),
                            Name = "Alice Williams",
                            PasswordHash = "$2a$11$h2avwvAUWu1EAxK3cco3Kuvop3oMI0o7ssYZGw2.J54Q0.ZpwENkO"
                        },
                        new
                        {
                            SellerId = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 379, DateTimeKind.Utc).AddTicks(5905),
                            Email = "charlie.brown@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 379, DateTimeKind.Utc).AddTicks(5911),
                            Name = "Charlie Brown",
                            PasswordHash = "$2a$11$VDPIEJty7BAzl/7c8AUL9O.MCdCiUBesGjc8Bv8W2V/YfxxlX6Lqm"
                        },
                        new
                        {
                            SellerId = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 508, DateTimeKind.Utc).AddTicks(8517),
                            Email = "diana.davis@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 508, DateTimeKind.Utc).AddTicks(8523),
                            Name = "Diana Davis",
                            PasswordHash = "$2a$11$di3coA.C43ZM2wGiYYul7uWa8yynIuT7MIQIujJat7hCHCqWIoI/G"
                        },
                        new
                        {
                            SellerId = 7,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 658, DateTimeKind.Utc).AddTicks(1297),
                            Email = "edward.miller@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 658, DateTimeKind.Utc).AddTicks(1303),
                            Name = "Edward Miller",
                            PasswordHash = "$2a$11$uotvRcIpGzaUMi/1T3FOYeshQWf.MQ5RfRuUwlILG1bDUJohx0fCC"
                        },
                        new
                        {
                            SellerId = 8,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 784, DateTimeKind.Utc).AddTicks(5862),
                            Email = "fiona.wilson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 784, DateTimeKind.Utc).AddTicks(5869),
                            Name = "Fiona Wilson",
                            PasswordHash = "$2a$11$1oegcXpIF92/yX/WXSdM7ecoLknQZmXP/z2L1r3XSht8x0XW07n5K"
                        },
                        new
                        {
                            SellerId = 9,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 36, 921, DateTimeKind.Utc).AddTicks(2015),
                            Email = "george.moore@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 36, 921, DateTimeKind.Utc).AddTicks(2026),
                            Name = "George Moore",
                            PasswordHash = "$2a$11$2AqGoKjJm3Ing8AYoTmFSON45O4pj.RxoRcQJ7y7paA59fhhV.Emy"
                        },
                        new
                        {
                            SellerId = 10,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 26, 37, 74, DateTimeKind.Utc).AddTicks(7090),
                            Email = "helen.taylor@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 26, 37, 74, DateTimeKind.Utc).AddTicks(7096),
                            Name = "Helen Taylor",
                            PasswordHash = "$2a$11$j1PhptgiwJrTpXKpTQp.PO1dZiqjIzGJ52XSCvkn9/yK7znn74AWG"
                        });
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.HasOne("OfferService.Domain.Entities.Seller", "Seller")
                        .WithMany("Offers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
