// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfferService.Infrastructure.Data;

#nullable disable

namespace OfferService.Infrastructure.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20260102141147_AddMissingColumns")]
    partial class AddMissingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.Property<long>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OfferId"));

                    b.Property<string>("AirbagsDeployed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AllTiresInflated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyPanelsIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("BuyerZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DrivetrainCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineTransmissionCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FloodFireDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InteriorIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMileageUnverifiable")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyOrFobAvailable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("MirrorsLightsGlassIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NoSQLIndexId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipTitleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerNetworkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("offered");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleBodyStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleBodyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleCabType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VehicleDoorCount")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleFuelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleTrim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleUsage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("WheelsRemoved")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WheelsRemovedDriverFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedDriverRear")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerRear")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkingBatteryInstalled")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OfferId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SellerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 53, DateTimeKind.Utc).AddTicks(8412),
                            Email = "john.doe@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 53, DateTimeKind.Utc).AddTicks(8417),
                            Name = "John Doe",
                            PasswordHash = "$2a$11$HNCCQYeZ1ATeQyyyhdTOk.2itJrBUc.BPJGRSjw3sVcihaqzVCbK."
                        },
                        new
                        {
                            SellerId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 208, DateTimeKind.Utc).AddTicks(4282),
                            Email = "jane.smith@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 208, DateTimeKind.Utc).AddTicks(4289),
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$//p.CBierACcyVGxkjss4ehmbmkpixS5S9uFUBQBIqNsHcfRWVVz6"
                        },
                        new
                        {
                            SellerId = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 365, DateTimeKind.Utc).AddTicks(2791),
                            Email = "bob.johnson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 365, DateTimeKind.Utc).AddTicks(2798),
                            Name = "Bob Johnson",
                            PasswordHash = "$2a$11$tg.DiJVlXNCiRUWTfX/9/.5UI0G9PK/kiWUAvKVe4ImiSl1hkaEjq"
                        },
                        new
                        {
                            SellerId = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 519, DateTimeKind.Utc).AddTicks(8701),
                            Email = "alice.williams@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 519, DateTimeKind.Utc).AddTicks(8709),
                            Name = "Alice Williams",
                            PasswordHash = "$2a$11$9OWhbbduUTnnlyv7a6FsZuszXKDBvwIqE21taB1E0.au.gimA0niK"
                        },
                        new
                        {
                            SellerId = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 673, DateTimeKind.Utc).AddTicks(1396),
                            Email = "charlie.brown@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 673, DateTimeKind.Utc).AddTicks(1404),
                            Name = "Charlie Brown",
                            PasswordHash = "$2a$11$ocgUeG/dKfbSIb4n9dTex.EqbiiHSKdPGT4gtb3DL94eLYpI.8iB2"
                        },
                        new
                        {
                            SellerId = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 826, DateTimeKind.Utc).AddTicks(3892),
                            Email = "diana.davis@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 826, DateTimeKind.Utc).AddTicks(3902),
                            Name = "Diana Davis",
                            PasswordHash = "$2a$11$dD4iY2hahVAaPy2LEYSsQumw4OJlfkAeS7/YodKqf/SFDZDxgitIO"
                        },
                        new
                        {
                            SellerId = 7,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 46, 979, DateTimeKind.Utc).AddTicks(5800),
                            Email = "edward.miller@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 46, 979, DateTimeKind.Utc).AddTicks(5806),
                            Name = "Edward Miller",
                            PasswordHash = "$2a$11$Z4Dre4brHqTBnTkMsVabk.fpsZqM1ml7ANScBuuJD3IPZqiWYvG62"
                        },
                        new
                        {
                            SellerId = 8,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 47, 132, DateTimeKind.Utc).AddTicks(8005),
                            Email = "fiona.wilson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 47, 132, DateTimeKind.Utc).AddTicks(8011),
                            Name = "Fiona Wilson",
                            PasswordHash = "$2a$11$IpBx353qIFa0/j1Aisv7g.kGjK7M9ND1Hjswu5.RT5eEq5lRypsQa"
                        },
                        new
                        {
                            SellerId = 9,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 47, 285, DateTimeKind.Utc).AddTicks(9351),
                            Email = "george.moore@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 47, 285, DateTimeKind.Utc).AddTicks(9356),
                            Name = "George Moore",
                            PasswordHash = "$2a$11$z7HJJ.1KyI8dzmz.wCggh.hhr5zyRIx4ofa/9I6VZxaBY2ibnSiuu"
                        },
                        new
                        {
                            SellerId = 10,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 11, 47, 441, DateTimeKind.Utc).AddTicks(9506),
                            Email = "helen.taylor@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 11, 47, 441, DateTimeKind.Utc).AddTicks(9520),
                            Name = "Helen Taylor",
                            PasswordHash = "$2a$11$cdDxXwmOwluiLgPLWpg1se.mJ9dugl8Mdu3x26W6X26vJ9Fidmxby"
                        });
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.HasOne("OfferService.Domain.Entities.Seller", "Seller")
                        .WithMany("Offers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
