// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OfferService.Infrastructure.Data;

#nullable disable

namespace OfferService.Infrastructure.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    partial class OfferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.Property<long>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OfferId"));

                    b.Property<string>("AirbagsDeployed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AllTiresInflated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyPanelsIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<string>("BuyerZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CarrierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DrivetrainCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EngineTransmissionCondition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FloodFireDamageFree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InteriorIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsMileageUnverifiable")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyOrFobAvailable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("MirrorsLightsGlassIntact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("NoSQLIndexId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipTitleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerNetworkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("offered");

                    b.Property<Guid?>("TransportId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleBodyStyle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleBodyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleCabType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VehicleDoorCount")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleFuelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleTrim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleUsage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VehicleZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("WheelsRemoved")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WheelsRemovedDriverFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedDriverRear")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerFront")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelsRemovedPassengerRear")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkingBatteryInstalled")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OfferId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SellerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 106, DateTimeKind.Utc).AddTicks(2848),
                            Email = "john.doe@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 106, DateTimeKind.Utc).AddTicks(2854),
                            Name = "John Doe",
                            PasswordHash = "$2a$11$hiwZ8KF9BDfMqUxmqQI/x.OLkVX.o47Z24GcFFBS44V68eAf6I58y"
                        },
                        new
                        {
                            SellerId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 259, DateTimeKind.Utc).AddTicks(9330),
                            Email = "jane.smith@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 259, DateTimeKind.Utc).AddTicks(9336),
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$/SUUBUyBWlWDqizOYZ4x9uxsmWRLvT7DBfTV8Moj2tiQuG6U0R1si"
                        },
                        new
                        {
                            SellerId = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 413, DateTimeKind.Utc).AddTicks(1537),
                            Email = "bob.johnson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 413, DateTimeKind.Utc).AddTicks(1541),
                            Name = "Bob Johnson",
                            PasswordHash = "$2a$11$sXY2OMNRndNtzVHoOaVGjOL3QlpwJ7N4DJPmtFpwez.AQi94IO/zu"
                        },
                        new
                        {
                            SellerId = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 574, DateTimeKind.Utc).AddTicks(4944),
                            Email = "alice.williams@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 574, DateTimeKind.Utc).AddTicks(4954),
                            Name = "Alice Williams",
                            PasswordHash = "$2a$11$WXsT6H4weMd963sEgCS0vehNk/Iwb3gS3ybfRhWocmq/lYguewEWa"
                        },
                        new
                        {
                            SellerId = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 727, DateTimeKind.Utc).AddTicks(3037),
                            Email = "charlie.brown@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 727, DateTimeKind.Utc).AddTicks(3041),
                            Name = "Charlie Brown",
                            PasswordHash = "$2a$11$M6QPrHMfQL3PhLj36okGlOpFVAiMYoMiKS6kWH9Dk8EiH2EVju9V6"
                        },
                        new
                        {
                            SellerId = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 853, DateTimeKind.Utc).AddTicks(3307),
                            Email = "diana.davis@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 853, DateTimeKind.Utc).AddTicks(3311),
                            Name = "Diana Davis",
                            PasswordHash = "$2a$11$CsO5CGIv1OZ2UYkfCap1xe2YQ6UkVuDtmSLkjBKJZ2gp7GeYN3Es6"
                        },
                        new
                        {
                            SellerId = 7,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 42, 978, DateTimeKind.Utc).AddTicks(9458),
                            Email = "edward.miller@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 42, 978, DateTimeKind.Utc).AddTicks(9459),
                            Name = "Edward Miller",
                            PasswordHash = "$2a$11$rb/YLOcz/1iXODkNi0unteDKce8E1CgNgJH7BWyq8iVVd5WjciFwy"
                        },
                        new
                        {
                            SellerId = 8,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 43, 104, DateTimeKind.Utc).AddTicks(5593),
                            Email = "fiona.wilson@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 43, 104, DateTimeKind.Utc).AddTicks(5598),
                            Name = "Fiona Wilson",
                            PasswordHash = "$2a$11$UzLSj3oKM.y/MpPAb3n.OuCqc0rrLZsGTSKGCd61vPihT3AvcQWmy"
                        },
                        new
                        {
                            SellerId = 9,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 43, 230, DateTimeKind.Utc).AddTicks(1657),
                            Email = "george.moore@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 43, 230, DateTimeKind.Utc).AddTicks(1659),
                            Name = "George Moore",
                            PasswordHash = "$2a$11$1RuKdk.ZJK59T818F5Bseeu5K7Im1sMSpNa4Z3ed/QqKxe.zw2SNe"
                        },
                        new
                        {
                            SellerId = 10,
                            CreatedAt = new DateTime(2026, 1, 2, 14, 39, 43, 356, DateTimeKind.Utc).AddTicks(1359),
                            Email = "helen.taylor@example.com",
                            LastModifiedAt = new DateTime(2026, 1, 2, 14, 39, 43, 356, DateTimeKind.Utc).AddTicks(1362),
                            Name = "Helen Taylor",
                            PasswordHash = "$2a$11$YmKJLz.FyCdJ4cZWxUowC.wH8TNxvv2.4KfrEU2vT4f4Rz4KGjyjy"
                        });
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Offer", b =>
                {
                    b.HasOne("OfferService.Domain.Entities.Seller", "Seller")
                        .WithMany("Offers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("OfferService.Domain.Entities.Seller", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
